apiVersion: apps/v1
kind: Deployment
metadata:
  name: {0}
  namespace: backend
  labels:
    kubegreeners.github.io/branch: "{0}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{0}"
  template:
    metadata:
      labels:
        name: "{0}"
    spec:
      containers:
        - name: application
          image: ghcr.io/kube-greeners/backend/backend:{0}
          env:
            - name: PROMETHEUS_URL
              value: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
            - name: SERVE_ADDRESS
              value: 0.0.0.0:8080
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      initContainers:
        - name: download-config-maps
          image: alpine:3.4
          command: [ "/bin/sh","-c" ]
          args: [ "apk add curl; apk add python3; cp /py/get_frontend.py .; python3 get_frontend.py" ]
          volumeMounts:
            - mountPath: "/py"
              name: init-py-script
              readOnly: true
      volumes:
        - name: init-py-script
          configMap:
            name: {0}-python
            items:
              - key: "get_frontend.py"
                path: "get_frontend.py"

---
apiVersion: v1
kind: Service
metadata:
  name: {0}-svc
  namespace: backend
  labels:
    kubegreeners.github.io/branch: "{0}"
spec:
  selector:
    name: {0}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
