apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{0}
  namespace: kube-green
  labels:
    kubegreeners.github.io/branch: "backend/{0}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "backend-{0}"
  template:
    metadata:
      labels:
        name: "backend-{0}"
    spec:
      containers:
        - name: application
          image: ghcr.io/kube-greeners/backend/backend:{0}
          env:
            - name: PROMETHEUS_URL
              value:  prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local
            - name: SERVE_ADDRESS
              value: 0.0.0.0:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-{0}-svc
  namespace: kube-green
  labels:
    kubegreeners.github.io/branch: "backend/{0}"
spec:
  selector:
    name: backend-{0}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      name: http
---
