name: Push Docker Images

on:
  push:
    branches: [ feature/*, master, bugfix/*, stylefix/*, dev, ci/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          echo "name=${github_ref/\//-}" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref_name }}
      - name: Publish Go Image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: backend
          build-context: .
          dockerfile: ./Dockerfile
          image-tag: ${{ env.name }}
      # Setup gcloud CLI
      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: kube-greeners
      - name: Patch Template
        run: |
          export TEMPLATE=$(cat ./k8s-template.yml)
          echo ${TEMPLATE//{0}/$name} >> k8s.yml
          echo $name

      - name: Deploy to K8S
        run: |
          gcloud container clusters get-credentials test-cluster --zone=europe-west1-b --project=kube-greeners
          echo $(kubectl get nodes)
          cat k8s.yml
          kubectl -n kube-green apply -f k8s.yml
        with:
          name: k8s-config
          path: k8s.yml




